### ISSUE TITLE
Delete self

### ISSUE THREAD

**Issue by FrederikSchaff** [marcov64/Lsd#9] opened 2018-10-02 13:30 UTC
It would be helpful if objects could delete themselves. This could be implemented with an additional flag. Once an object is decided to be deleted, it is ignored in all what follows and at the end of the simulation step there is some kind of garbage collection.

**Comment by MCP1** [comment] 2018-10-02 19:29
Hi Frederick.
I didn't have time to test but a quick inspection of the code doesn't show any obvious reason a variable's equation could not delete the object containing it. 
Can you elaborate more on a test model where the problem shows up?

**Comment by marcov64** [comment] 2018-10-02 19:38
Marcelo,
in the old version the if a variable executing its equation deleted the object the system crashed because after the execution of the equation for a variable an object is used to perform certain tasks, e.g. check if the results have to be saved and seek the "next" object to refresh its variables. I don't know if the new version updated the stacklog mechanism removing this limitation.

**Comment by MCP1** [comment] 2018-10-02 20:08
Neither do I... That is why I asked a sample model where the problem can be reproduced and more easily fixed ;-)

**Comment by MCP1** [comment] 2018-10-03 15:01
Thanks for the test model! For now I introduced a proper error message in this situation.
Will look for a fix later.

**Comment by MCP1** [comment] 2018-10-04 19:45
Should be fixed now. Please note that the requirement to keep at least one instance of each object remains.

**Closed by MCP1** 2018-10-04 19:45 UTC
Labels: bug, enhancement, fixed
