### ISSUE TITLE
Stat when items are deleted and added (?)

### ISSUE THREAD

**Issue by FrederikSchaff** [marcov64/Lsd#36] opened 2019-01-31 12:07 UTC
I encountered some issues where STAT in situation where there where no instances of an object did not work properly. I built a small test model (attached) to haunt the problem. Basically, it can even happen when there are still instances left. If one of the variables triggered by STAT has the ability to delete the object, STAT does not work properly. The work-around is to run a CYCLE over the variable which can delete the object first and then run STAT (this is commented out in the example).

I suggest to fix it by adding **four** new lines to `double object::stat( char const* lab, double* r )`, before the calculation of the stats, this worked for me the same way as running the cycle by hand.
```cpp
    r[ 0 ] = r[ 1 ] = r[ 2 ] = r[ 3 ] = r[ 4 ] = 0;

    if (cv != NULL){
        cv = search_var( this, lab, true, no_search );
        for ( cur = cv->up; cur != NULL; cur = go_brother( cur ) ) { cur->cal (lab, 0); } //update first.
    }
    cv = search_var( this, lab, true, no_search ); //search again, the original one may be dead.
```

A second problem is that the blueprint search is not working. Fixing the line a bit further down helps:
```cpp
//cv = blueprint->search_var( this, lab, true, no_search );
cv = blueprint->search( this->label )->search_var( this, lab, true, no_search );
```
fixed this issue for me.

There may be other positions with similar problems.

[teststat.zip](https://github.com/marcov64/Lsd/files/2817011/teststat.zip)

**Comment by MCP1** [comment] 2019-02-17 20:50
I personally think the proposed workaround is not the best approach. It significantly penalyzes the time to execute STAT in any larger model. And, to be consistent, It would have to be implemented also in SUM, WHAVG, COUNT, SEARCH ... Also, there are other possible race conditions not caught by it (imagine the parent of the parent container being deleted).

I believe the worst problem is the very idea of deleting objects while they may still contain stuff which may be in use by other computations. By any account, it is responsibility of the modeler to avoid this type of data race. C++ offers very sophisticated tools to implement semaphores for this purpose, if required. I think it is really impossible to LSD to try to track all the possible inconsistent situations that can be caused by problematic code. That is the same philosophy employed in any high performance framework, like C++ STL.

**Comment by MCP1** [comment] 2019-02-17 20:53
However, the indication of when such data races may create problems is the important point here. To make this more clear to the modelers, I added a new warning section in the DELETE macro documentation, clearly explaining the necessity of ensuring the data in any deleted object is no longer required by any possibly running computation.

**Comment by FrederikSchaff** [comment] 2019-02-18 08:08
I see the point. However, the problem with the blue-print is still there, right?

**Comment by MCP1** [comment] 2019-02-18 16:55
Sorry Frederik, I forgot to comment on the second point. In fact, I didn't understand what is the problem. What do you mean by "the blueprint search is not working"? Are you proposing to change object.cpp:2466? Why? I just tested STAT on a no instance object variable and it seems to be working as expected.

**Comment by FrederikSchaff** [comment] 2019-02-19 06:58
Hmm, for the test-model attached in my first post to work correctly I needed to do both changes, i.e. the first run to update the chain of objects and then alter the blueprint search to first search for the blueprint object that contains the variable and then the variable. 

However, I tested it again and now it isn't relevant anymore. Perhaps some changes in 7.1.1-beta or I don't know. Thanks for checking again, too!

**Comment by FrederikSchaff** [comment] 2019-02-19 08:09
A few more comments in case this comes up in future...

I checked again what exactly happens when STAT (or similar) triggers the deletion of variables. Basically, the problem is in variab.cpp::cal() where:

```
under_computation = false;
	
// if there is a pending deletion, try to do it now
	if ( wait_delete != NULL )
		wait_delete->delete_obj( );

	return val[ 0 ];	// by default the requested value is the last one, not yet computed
```
The return does not work anymore, because the object is now deleted. It is not trivial to change this behaviour or provide a better error message, though, I agree now. I tried with a helper that checks if _this->up_ or a parent object (up->up, etc., until root) is to be deleted, but then the self-deleting doesn't (obviously) work anymore and it is always flagged that a deleting process is already pending.... 

If there was a way to provide better clues in the sigsev message in LSD on potential problems, this could help with debugging, though.

**Comment by FrederikSchaff** [comment] 2019-02-20 18:01
I have to reopen it, sadly. I tried now to re-run a model with a zero-instance and then use stat. It does not work correctly. The problem here is directly related to the blueprint 
```
//cv = blueprint->search_var( this, lab, true, no_search );
cv = blueprint->search( this->label )->search_var( this, lab, true, no_search );
```
I use the STAT command on a variable that has just been deleted prior to calling the stat (but in another EQUATION) and run into this problem. I can circumvent it by only running `STAT` if `COUNT` on the same variable return `> 0`. I guess the problem has to do with search_var, but I am not sure. I also tried to replicate the problem in a version of the test model that is structurally more similar, but to no avail. Perhaps it is safe to change it accordingly.  The problem is exactly the same with `SD`, i.e. there the `search(this->label)`needs to be added to the blueprint search, too.

**Comment by FrederikSchaff** [comment] 2019-02-20 18:09
[teststat.zip](https://github.com/marcov64/Lsd/files/2885921/teststat.zip)
I was able to replicate it in a test model. The problem is within search_var, I guess. If you set a break point to error_hard you can easily trace the problem. I needed to move the complete model one level below root to replicate the error.

**Comment by MCP1** [comment] 2019-02-25 00:59
Thanks for the test model Frederik. Should be fixed now.

**Comment by FrederikSchaff** [comment] 2019-02-28 08:28
Hi there,

unfortunately there is still a strange error. If you run the model under gdb, an error is flagged in variab.cpp.

Changing the default behaviour as follows helps:
```
    // if there is a pending deletion, try to do it now
    if ( wait_delete != NULL ) {
        double buffer = val[ 0 ];
        wait_delete->delete_obj( );
        return buffer;
    }

	return val[ 0 ];	// by default the requested value is the last one, not yet computed
```

Then, in the test-model an error is flagged where the CYCLE is used on zero-instance objects, but this is informative enough (in my opinion) and using CYCLE_SAFE solves the problem.

**Comment by MCP1** [comment] 2019-02-28 13:13
Yes, I have noticed that. But the problem is in the test model itself, which creates a race condition by deleting objects under computation, which is not supported. To fix it, simply move the DELETE from the equation where it is to the CYCLE before invoking STAT, and turn the CYCLE into CYCLE_SAFE.

And yes, there is different behavior when you run it under GDB or not. But here we can't do anything, as we do not manage how system signals are trapped by GDB and the compiler library (when not running under GDB).

**Closed by MCP1** 2019-02-28 13:13 UTC
Labels: bug
