### ISSUE TITLE
LSD IS NOT WORKING IN MAC 10.14 MOJAVE

### ISSUE THREAD

**Issue by arthurcb** [marcov64/Lsd#8] opened 2018-09-24 20:30 UTC
Dear Marco, I've updated to macOS Mojave and after that the LSD screens look strange - I can't see the text elements nor the icons (please see attached screenshot). 
Is there anything I can do to fix that? Will it be a code update for that?
Thanks in advance and best regards.

![screen shot 2018-09-24 at 17 25 47](https://user-images.githubusercontent.com/7797192/45977208-40e3f300-c01f-11e8-9611-c7c659323ecd.png)

**Comment by MCP1** [comment] 2018-09-24 22:38
Another thing I just noticed. It seems you're using lmmOSX to launch LMM/LSD. lmmOSX is the now deprecated version of LMM which uses the old/buggy Tcl/Tk implementations which comes with macOS.
As recommended in Readme.txt (pleas take a look), recent versions of macOS should use LMM.app (which shows just as LMM in Finder), AFTER you execute once the add-shortcut-mac.sh script in Terminal (which not just create a shortcut but also fix some security requirements in new macOS versions).

**Comment by arthurcb** [comment] 2018-09-24 22:57
Dear Marcelo,
1. I am using Tcl/Tk version 8.6 (8.6.7).
2 and 3. No matter the way (dark theme or light theme) I open LSD I get an error:
a) If I launch lmmOSX I get the first error (that is the version I've been using for a couple of months). I am able to compile and run model, but due to the graphic error, it is not possible to use LSD.
b) If I launch LMM.app I get the attached Tcl error when I try to compile and run a model.
![screen shot 2018-09-24 at 18 26 54](https://user-images.githubusercontent.com/7797192/45983477-23208900-c033-11e8-80ff-1f72b0c6f126.png)
I have executed the add-shortcut-mac.sh script in Terminal. I'm not aware what this issue root cause could be - I must confess I have been using the lmmOSX version since I started learning LSD. I first noticed this error when I tried to execute it after I updated to Mojave.
![screen shot 2018-09-24 at 19 52 13](https://user-images.githubusercontent.com/7797192/45983542-5a8f3580-c033-11e8-87ad-061025b581f7.png)

**Comment by MCP1** [comment] 2018-09-24 23:18
You CANNOT freely switch from lmmOSX to LMM.app on the same model, the system and model configurations are different. 
Do the following:
1. Launch LMM.app (and not lmmOSX, which you better delete as it is deprecated).
2. Open your existing model and select/copy all code to the clipboard (Ctrl+c).
3. Create a new (empty) model, so we can migrate the existing model to it (name it accordingly).
4. Paste (Ctrl+v) your code into the new model (make sure you are in the "Show Equations" view).
5. Open "Model>System Options" and click on button "Default MacOS".
6. Recompile your model.
7. If you have .lsd configuration files, you can safely move (just) those from the old model folder to the new model one.
8. Delete the old model folder, to avoid future confusion.

**Comment by arthurcb** [comment] 2018-09-24 23:44
That is clear now, thank you very much. I can now compile and run my code thru LMM.app without errors. However, I only get a black screen when LSD opens. 
What am I missing now?
![screen shot 2018-09-24 at 20 43 21](https://user-images.githubusercontent.com/7797192/45985023-95e13280-c03a-11e8-8583-07f99bd4d535.png)

**Comment by MCP1** [comment] 2018-09-24 23:48
Does the LSD Browser window open? Or is it just the Log window that shows up?

**Comment by MCP1** [comment] 2018-10-10 23:31
I guess you solved your problem. Closing issue.

**Comment by arthurcb** [comment] 2018-10-11 02:10
Hi Marcelo - I am sorry, but I think I did not get a notification from your last message 16 days ago. 
I only get the LSD Log window when I try to compile and run a model.

**Comment by MCP1** [comment] 2018-10-11 13:48
Hi Arthur. Thanks for the video. The symptom is clear but the problem is that I can't reproduce it here.
It seems to be an Tcl/Tk problem. Could you please check if a LSD.err file was produced inside the model folder (~/Lsd/Example/...) and attach it here?
Have you changed any Tcl/Tk configuration in your system or tried to manually install another version? If so, try to restore/remove any change. LSD should work out-of-the box in any macOS version newer than 10.9.
Last, I suggest you fully remove LSD and install the latest 7.1-beta-9 version.

**Comment by MCP1** [comment] 2018-10-11 14:47
Just deleting the folder where you are going to reinstall is enough. Your steps are correct. Most likely we have to wait some time until we have access to a Mojave machine to try to reproduce your problem and find a fix. Sorry for that.

**Comment by MCP1** [comment] 2018-11-18 19:01
LSD 7.1-Belta-13 was upgraded to Tcl/Tk 8.6.9.1, which is reported to solve the black screen problem for code compiled in macOS 10.14 Mojave, like the LSD model browser.
As my test virtual machine still doesn't support Mojave, I can't test it. So I ask Arthur, Marco or other nice user to test and report the results here.
Thanks!

**Comment by arthurcb** [comment] 2018-11-20 03:46
Dear Marcelo, it is working for me now in macOS 10.14 Mojave! Thank you very much for your kind reminder!

**Comment by MCP1** [comment] 2018-11-20 12:57
Thanks for the feedback!

**Closed by MCP1** 2018-11-20 12:57 UTC
Labels: fixed
